IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'CliniquePlusDB')
 BEGIN
    CREATE DATABASE CliniquePlusDB;
	END

	
	USE CliniquePlusDB;
	
	
-- CREATIONS DU SHEMA

	CREATE SCHEMA Clinique;


	-- CREATION DU TABLE SPECIALIE
CREATE TABLE	CLINIQUE.SPECIALITE(
ID_SPECIALITE   INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOM_SPECIALITE      VARCHAR(30)   CHECK( NOM_SPECIALITE IN('GYNECOLOGUE','INFIRMIERE','CHIRURGIE','CARDIOLOGUE','PEDIATRIE','LABORATINE')),
TARIF  DECIMAL(10,2)  NOT NULL 
);


--CREATIONS DU TABLE MEDECINS

CREATE TABLE CLINIQUE.MEDECINS(
ID_MEDECINS  INT IDENTITY(1,1)  PRIMARY KEY,
MATRICULE       NVARCHAR(59)  NOT NULL CHECK (MATRICULE LIKE 'MED-[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9]'),
NOM          VARCHAR(50)   NOT NULL ,
PRENOM   VARCHAR(40)  NOT NULL,
SEXE    CHAR(1)  CHECK (SEXE IN ('F','M')),
TELEPHONE     VARCHAR(20)  UNIQUE   NOT NULL,
EMAIL     NVARCHAR(50) UNIQUE  CHECK ( EMAIL LIKE '%@%.%'),
DATE_NAISSANCE     DATE NOT  NULL,
ADRESSE          VARCHAR(50) NOT NULL,
DATE_EMBAUCHE DATE  DEFAULT GETDATE() NOT NULL,
SALAIRE    DECIMAL(10,3)    NOT NULL,
ID_SPECIALITE    INT ,
CONSTRAINT FK_MEDECINS_SPECIALITE
FOREIGN KEY(ID_SPECIALITE)
REFERENCES CLINIQUE.SPECIALITE(ID_SPECIALITE)
ON DELETE CASCADE
ON UPDATE CASCADE
);

 --CREATIONS DU TABLE PATIENTS

  CREATE TABLE CLINIQUE.PATIENTS(
  ID_PATIENTS   INT IDENTITY(1,1)   PRIMARY KEY ,
  NUMERO_PATIENT VARCHAR(20) NOT NULL CHECK (NUMERO_PATIENT LIKE 'PAT-[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9]'),
  NOM    VARCHAR(40)     NOT NULL,
  PRENOM  VARCHAR(20)  NOT NULL,
  SEXE    CHAR(1)   CHECK ( SEXE IN('F','M')),
  DATE_NAISSANCE   DATE  NOT NULL,
   AGE      AS(DATEDIFF (YEAR,DATE_NAISSANCE,GETDATE())),
  EMAIL    NVARCHAR(40)  UNIQUE CHECK( EMAIL LIKE'%@%.%'),
  TELEPHONE     VARCHAR(30)  UNIQUE  NOT NULL,
  ADRESSE   VARCHAR(100) NOT NULL,
  G_SANGUIN  NVARCHAR(10) NOT NULL,
  DATE_INSCRIPTIONS  DATE   DEFAULT GETDATE() NOT NULL
  );
  --CREATIONS DU TABLE  CONSULTATIONS

   CREATE TABLE CLINIQUE.CONSULTATIONS(
   ID_CONSULTATIONS     INT IDENTITY(1,1)  PRIMARY KEY,
   DATE_CONSULTATIONS     DATE  DEFAULT GETDATE(),
   MOTIF            VARCHAR(70)  NOT NULL,
   DIANGOSTIC     TEXT,
   STATUT    VARCHAR(40)   CHECK (STATUT IN('EN ATTENTE','ANNULER','TERMINER')),
   ID_MEDECINS  INT ,
   ID_PATIENTS  INT ,
   CONSTRAINT  FK_CONSULTATIONS_MEDECINS
   FOREIGN KEY (ID_MEDECINS)
   REFERENCES CLINIQUE.MEDECINS(ID_MEDECINS),
   CONSTRAINT  FK_CONSULTATIONS_PATIENTS
   FOREIGN KEY ( ID_PATIENTS)
   REFERENCES   CLINIQUE.PATIENTS(ID_PATIENTS)
   ON DELETE CASCADE
   ON UPDATE CASCADE
   );

-- CREATIONS DU TABLE MEDICAMENT

   CREATE TABLE CLINIQUE.MEDICAMENTS(
   ID_MEDICAMENTS  INT  IDENTITY(1,1)  PRIMARY KEY,
   NOM_MEDICAMENT    NVARCHAR(30)  NOT NULL,
   DCI    VARCHAR(50) ,
   CATEGORIE   VARCHAR(30) CHECK(CATEGORIE IN ('ANTIACIDES','ANTITUSSIFS','ANTIGOUTTEUX','ANTIBIOTIQUE')),
   PRIX_UNITAIRE  DECIMAL(10,2)  NOT NULL,
   STOCK   INT  DEFAULT 0
   );

   --CRATIONS DU TABLE PRECRIPTION

    CREATE TABLE CLINIQUE.PRESCRIPTION  (
	ID_PRESCRIPTION  INT IDENTITY(1,1)  PRIMARY KEY,
	POSOLOGIE   VARCHAR(30)  NOT NULL,
	DUREE_JOUR     INT NOT NULL,
	QUANTITE  INT NOT NULL,
	ID_MEDICAMENTS   INT,
	ID_CONSULTATIONS   INT,
	  CONSTRAINT FK_PRESCRIPTION_MEDICAMENTS
	  FOREIGN KEY (ID_MEDICAMENTS)
	  REFERENCES CLINIQUE.MEDICAMENTS(ID_MEDICAMENTS),
	  CONSTRAINT FK_PRESCRIPTION_CONSULTATIONS
	  FOREIGN KEY (ID_CONSULTATIONS)
	  REFERENCES CLINIQUE.CONSULTATIONS(ID_CONSULTATIONS)
	  ON DELETE CASCADE 
	  ON UPDATE CASCADE
	  );

	  --CREATIONS DU TBALE FACTURE

	  CREATE TABLE CLINIQUE.FACTURE(
	  ID_FACTURES  INT IDENTITY(1,1)  PRIMARY KEY ,
	  MONTANT_BASE    DECIMAL CHECK( MONTANT_BASE>0) NOT NULL,
	  REMISE     DECIMAL(10,5) CHECK(REMISE BETWEEN 0 AND 100) DEFAULT 0 NOT NULL,
	  MONTANT_NET   AS (MONTANT_BASE*(1-REMISE/100)) PERSISTED,
	  STATUT VARCHAR(50)   DEFAULT 'EN ATTENT' CHECK(STATUT IN('EN ATTENT','IMPAYER','PAYER')),
	  DATE_FATURE   DATE  DEFAULT GETDATE(),
	  ID_CONSULTATIONS  INT NOT NULL,
	  CONSTRAINT FK_FACTURE_CONSULTATIONS
	  FOREIGN KEY(ID_CONSULTATIONS)
	  REFERENCES CLINIQUE.CONSULTATIONS(ID_CONSULTATIONS)
	  );

	 
	 --CREATIOON  D'INDEX

	  CREATE NONCLUSTERED INDEX IDX_PATIENTS_NOM
	  ON CLINIQUE.PATIENTS(NOM);
	  
	  

	  CREATE   NONCLUSTERED INDEX IDX_CONSULTATIONS_PATIENTS
	  ON CLINIQUE.CONSULTATIONS(ID_CONSULTATIONS);

	  CREATE  NONCLUSTERED INDEX IDX_MEDICAMENTS_NOM_MEDICAMENT
	  ON CLINIQUE.MEDICAMENTS(NOM_MEDICAMENT);


--CREATION VIEW
	  CREATE VIEW CLINIQUE.VUE_CONSULTATIONS_DETAIL AS
	  SELECT C.ID_CONSULTATIONS,P.NOM + ' ' + P.PRENOM AS NOM_COMPLET_PATIENTS,
	  M.NOM AS NOM_MEDECIN,
	  S.NOM_SPECIALITE AS SPECIALITE_MEDECIN,
	  C.DATE_CONSULTATIONS,
	  C.MOTIF,C.STATUT FROM CLINIQUE.CONSULTATIONS C JOIN CLINIQUE.PATIENTS P ON C.ID_PATIENTS=P.ID_PATIENTS
	  JOIN CLINIQUE.MEDECINS M ON C.ID_MEDECINS  = M.ID_MEDECINS  JOIN CLINIQUE.SPECIALITE S ON M.ID_SPECIALITE =S.ID_SPECIALITE;

	 --AJOUT DU COLONNE DATE_FACTURE DANS TABLE Facture

	  ALTER TABLE CLINIQUE.FACTURE
ADD DATE_FACTURE DATE DEFAULT GETDATE();


 --CREATIONS VIEW
	  CREATE VIEW CLINIQUE.VUE_FACTURE_IMPAYEES  AS
	  SELECT F.ID_FACTURES, P.NOM  AS NOM_PATIENTS, P.TELEPHONE,F.MONTANT_NET, F.DATE_FACTURE
	  FROM CLINIQUE.FACTURE AS F  INNER JOIN CLINIQUE.PATIENTS P ON F.ID_CONSULTATIONS= P.ID_PATIENTS
	  INNER JOIN CLINIQUE.CONSULTATIONS AS C ON F.ID_FACTURES =C.ID_CONSULTATIONS
	  WHERE F.STATUT = 'IMPAYER';
	  

	 



	  --AJOUT DU COLONNE NOTES_INTERNES DANS LA TABLE CONSULTATIONS
	  ALTER TABLE CLINIQUE.CONSULTATIONS 
	  ADD NOTES_INTERNES NVARCHAR(MAX) DEFAULT 'NOTEE ENCOURE DE VEIRFICATIONS' ;

	  -- AJOUT DU COLONNE SPECIALISATIONS_COMPLEMENTAIRES DANS LA TABLE MEDECINS
	  ALTER TABLE ClINIQUE.MEDECINS
	  ADD SPECIALISATIONS_COMPLEMENTAIRE NVARCHAR(100);

	  --AJOUUT COLONNE DERNIER_MAJ DANS LA TABLE PATIENTS
	  ALTER TABLE CLINIQUE.PATIENTS 
	  ADD DERNIER_MAJ DATETIME DEFAULT GETDATE();

	  --MODIFICATIONS DU COLONNE ADRESSE
	  ALTER TABLE CLINIQUE.PATIENTS
	  ALTER COLUMN ADRESSE NVARCHAR(MAX);
	  -- AJOUTER COLONNE STATUT DANS MEDECINS
	  ALTER TABLE CLINIQUE.MEDECINS
	  ADD STATUT VARCHAR(20) CHECK (STATUT IN ('ACTIF','INACTIF','EN CONGE','SUSPENDU'));

  	  -- AJOUT DU CONTRAINT 
	  ALTER TABLE CLINIQUE.PATIENTS 
	  ADD CONSTRAINT CK_PATIENTS_DATE_NAISSANCE
	  CHECK (DATE_NAISSANCE <'2026-03-20');

	

	 --CREATIONS DU TABLE AUDIT_CONNEXIONs
	  
	  CREATE TABLE CLINIQUE.AUDIT_CONNEXIONS(
	  ID_AUDIT   INT IDENTITY(1,1) PRIMARY KEY ,
	  UTILISATEUR   NVARCHAR(300) NOT NULL,
	  DATE_ACTION DATETIME  NOT NULL DEFAULT GETDATE(),
	  TYPE_ACTION NVARCHAR(30) NOT NULL CHECK ( TYPE_ACTION IN('CONECXION','DECONNEXION','MODIFICATION')),
	  TABLE_CIBLE NVARCHAR(200) NULL
	  );

--INSERTION SPECIALITER

INSERT INTO CLINIQUE.SPECIALITE (NOM_SPECIALITE, TARIF)
VALUES
('GYNECOLOGUE', 2500.00),
('INFIRMIERE', 1500.00),
('CHIRURGIE', 4000.00),
('CARDIOLOGUE', 3000.00),
('PEDIATRIE', 2000.00),
('LABORATINE', 1800.00),
('CARDIOLOGUE', 3200.00);

-- INSERTION DU TABLE MEDCINS

INSERT INTO CLINIQUE.MEDECINS
(MATRICULE, NOM, PRENOM, SEXE, TELEPHONE, EMAIL, DATE_NAISSANCE, ADRESSE, DATE_EMBAUCHE, SALAIRE, ID_SPECIALITE)
VALUES
('MED-0000-001','PHAWENS','JEAN','M','50934332312','JEANPHAWENS@GMAIL.COM','1980-05-12','CITE MILITAIRE','2020-01-15',35000.000,1),
('MED-0000-002','DURAND','MARIE','F','50932234568','MARIEDURAND@OUTLOOK.FR','1985-07-20','VERNET#2','2021-03-10',36000.000,3),
('MED-0000-003','LOUIS','ANDRE','M','509441234569','ANDRELOUIS@GMAIL.COM','1978-09-25','PORT-SALUT','2019-06-01',34000.000,6),
('MED-0000-004','CHARLES','SOPHIE','F','509315434570','SOPHIECHARLES@YAHOO.FR','1990-11-11','TORBECK','2024-02-18',33000.000,2),
('MED-0000-005','FRANCOIS','PAUL','M','509551234571','PAULFRANCOIS@GMAIL.COM','1999-03-30','DEXIA','2015-09-05',37000.000,5),
('MED-0000-006','MARTIN','CLAIRE','F','509561234572','CLAIREMARTIN@GMAIL.COM','2004-12-14','PONT-SALOMON','2020-07-22',35500.000,3),
('MED-0000-007','ROBERT','DAVID','M','509361234573','DAVIDROBERT@YAHOO.FR','2000-04-09','QUANCE','2017-05-12',38000.000,2),
('MED-0000-008','JOSEPH','ANNE','F','509372234574','ANNEJOSEPH@GMAIL.COM','1992-08-19','MARCABEE','2025-11-03',32500.000,4),
('MED-0000-009','GLEMAUD','EZECHIEL','M','509443334575','GLEMAUDEZECHIEL@GMAIL.COM','2001-01-22','BERGAUD','2019-04-17',34500.000,5),
('MED-0000-010','PAUL','NATHALIE','F','5091234576','NATHALIEPAUL@GMAIL.COM','2005-06-27','BOUJOLIE','2022-09-09',33500.000,6);

--INSRTION DU TABLE PATIENT


INSERT INTO CLINIQUE.PATIENTS(NUMERO_PATIENT, NOM, PRENOM, SEXE, DATE_NAISSANCE, EMAIL, TELEPHONE, ADRESSE, G_SANGUIN, DATE_INSCRIPTIONS)
VALUES
('PAT-1980-001','LOUDY','MARIE','F','1980-05-12','MARIELOUDY@GMAIL.COM','50945324312','BARBOIS','A+','2020-01-15'),
('PAT-1990-002','PIERRE','LOUIS','M','1990-07-20','LOUISPIERRE@GMAIL.COM','5095543215','LES ANGLAIS','O-','2024-03-10'),
('PAT-1975-003','DURAND','SOPHIE','F','1975-09-25','SOPHIEDURAND@GMAIL.COM','50933215654','AQUIN','B+','2019-06-01'),
('PAT-2000-004','CHARLES','MAX','M','2000-11-11','CHARLESMAX@GMAIL.COM','50956432321','DURMONT','AB+','2023-02-18'),
('PAT-1982-005','FRANCOIS','RIGODON','M','1982-03-30','RGODONFRANCOIS@YAHOO.FR','50955432123','BORMONT','A-','2018-09-05'),
('PAT-1987-006','MARTIN','CLAIRE','F','1987-12-14','CLAIREMARTIN@GMAIL.COM','50932232454','PORT-SALUT','O+','2020-07-22'),
('PAT-1972-007','ROBERT','DAVID','M','1972-04-09','DAVIDROBERT@GMAIL.COM','509443426565','CARPENTIR','B-','2015-05-12'),
('PAT-1992-008','JOSEPH','ANNE','F','1992-08-19','ANNEJOSEPH@GMAIL.FR','50944352426','SIMON','AB-','2021-11-03'),
('PAT-1984-009','SIMON','SAM','M','1984-01-22','SAMSIMON@GMAIL.COM','50944343232','PONT-SALOMON','A+','2019-04-17'),
('PAT-1989-010','TOYO','DAANA','F','1989-06-27','TOYODAANA@GMAIL.COM','50933226576','K-CIEL','O-','2023-09-09'),
('PAT-1978-011','MICHEL','JULIEN','M','1978-02-14','JULIENMICHEL@YAHOO.FR','50955454343','MARCON','B+','2016-05-20'),
('PAT-1995-012','REMY','CAROLINE','F','1995-10-05','CAROLINEREMY@OUTLOOK.FR','50931545765','VARLLERS','A-','2023-01-11'),
('PAT-1981-013','GIRARD','PHILIPPE','M','1981-12-01','PHILIPPEGIRARD@YAHOO.FR','50956543256','COTEAUX','O+','2018-08-30'),
('PAT-1976-014','LAROCHE','ISABELLE','F','1976-06-18','ISABELLELAROCHE@OUTLOOK.FR','5093756454','BOLLIER','AB+','2017-04-25'),
('PAT-2002-015','NOEL','CHRISTOPHE','M','2002-09-09','CHRISTOPHENOEL@OUTLOOK.FR','50943245435','ANNIRQUET','B-','2024-02-02'),
('PAT-2004-016','JEAN','LOUIS-PHAWENSIA','F','2004-04-12','JEANPAWENSIAN@GMAIL.COM','50937323301','RUE TOUSSAIT LOUVERTURE','O+','2023-02-03'),
('PAT-2005-016','CARL','LOVENSKY','M','2005-07-23','CARL@GMAIL.COM','50931223465','CARFFOUT-THOMAS','A+','2023-01-20'),
('PAT-2000-017','ROSE','MARIE','F','2000-01-15','MARIEROSE@YAHOO.FR','50932345678','BOLLIER','B-','2020-12-12'),
('PAT-2003-018','SOPHIA','HERLINE-JEAN','F','2003-09-30','SJENAHERLINE@GMAIL.COM','509321090042','BOUJOLIE','AB+','2021-02-03'),
('PAT-2001-019','MARC','GERVENS','M','2001-11-20','RIGODON32@GMAIL.COM','509401008005','BREFET','O-','2023-02-01');

--INSERTION CONSULTATIONS
INSERT INTO CLINIQUE.CONSULTATIONS
(DATE_CONSULTATIONS, MOTIF, DIANGOSTIC, STATUT, ID_MEDECINS)
VALUES
('2020-01-15','CONTROLE CARDIAQUE','HYPERTENSION','EN ATTENTE',2),
('2024-03-10','SUIVI PEDIATRIQUE','GRIPPE','TERMINER',10),
('2019-06-02','CONSULTATION GENERALE','ANEMIE','ANNULER',3),
('2023-03-18','EXAMEN OPHTALMOLOGIQUE','MYOPIE','EN ATTENTE',4),
('2018-09-05','CONSULTATION GYNECOLOGIQUE','SUIVI POST-OPERATOIRE','TERMINER',5),
('2020-07-22','CONSULTATION DERMATOLOGIQUE','ALLERGIE CUTANEE','EN ATTENTE',6),
('2015-05-12','CONSULTATION NEUROLOGIQUE','MIGRAINE','ANNULER',7),
('2021-11-03','CONSULTATION ORTHOPEDIQUE','FRACTURE','TERMINER',4),
('2023-01-23','CONSULTATION PEDIATRIQUE','ASTHME','EN ATTENTE',1),
('2024-03-10','CONSULTATION CARDIOLOGIQUE','ANGINE DE POITRINE','TERMINER',1),
('2019-04-17','CONSULTATION GENERALE','DIABETE','ANNULER',3),
('2023-09-09','CONSULTATION OPHTALMOLOGIQUE','CATARACTE','EN ATTENTE',4),
('2016-05-20','CONSULTATION GYNECOLOGIQUE','SUIVI PRENATAL','TERMINER',5),
('2023-01-11','CONSULTATION DERMATOLOGIQUE','ECZEMA','ANNULER',6),
('2018-08-30','CONSULTATION NEUROLOGIQUE','EPILEPSIE','EN ATTENTE',7),
('2023-02-14','CONSULTATION ORTHOPEDIQUE','ARTHROSE','TERMINER',2),
('2024-02-02','CONSULTATION PEDIATRIQUE','VARICELLE','ANNULER',1),
('2023-03-01','CONSULTATION CARDIOLOGIQUE','INSUFFISANCE CARDIAQUE','EN ATTENTE',8),
('2023-03-03','CONSULTATION GENERALE','HYPOTENSION','TERMINER',3),
('2023-01-23','CONSULTATION OPHTALMOLOGIQUE','GLAUCOME','ANNULER',4);

--MIS A JOUR ID_PATIENTS DANS CONSULTATIONS

UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 1
WHERE ID_CONSULTATIONS = 12;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 2
WHERE ID_CONSULTATIONS = 13;

UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 3
WHERE ID_CONSULTATIONS = 14;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 4
WHERE ID_CONSULTATIONS = 15;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 5
WHERE ID_CONSULTATIONS = 16;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 6
WHERE ID_CONSULTATIONS = 17;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 7
WHERE ID_CONSULTATIONS = 18;

UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 8
WHERE ID_CONSULTATIONS = 19;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 1
WHERE ID_CONSULTATIONS = 20;

UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 1
WHERE ID_CONSULTATIONS = 21;

UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 3
WHERE ID_CONSULTATIONS = 22;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 4
WHERE ID_CONSULTATIONS = 23;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 5
WHERE ID_CONSULTATIONS = 24;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 6
WHERE ID_CONSULTATIONS = 25;

UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 7
WHERE ID_CONSULTATIONS = 26;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 2
WHERE ID_CONSULTATIONS = 27;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 8
WHERE ID_CONSULTATIONS = 28;


UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 1
WHERE ID_CONSULTATIONS = 29;

UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 4
WHERE ID_CONSULTATIONS = 30;

UPDATE CLINIQUE.CONSULTATIONS
SET ID_PATIENTS = 4
WHERE ID_CONSULTATIONS = 31;

--update statut medecins

UPDATE CLINIQUE.MEDECINS
SET STATUT = 'ACTIF'
WHERE ID_MEDECINS = 1;

UPDATE CLINIQUE.MEDECINS
SET STATUT = 'EN CONGE'
WHERE ID_MEDECINS = 2;

UPDATE CLINIQUE.MEDECINS
SET STATUT = 'ACTIF'
WHERE ID_MEDECINS = 3;

UPDATE CLINIQUE.MEDECINS
SET STATUT = 'SUSPENDU'
WHERE ID_MEDECINS = 4;

UPDATE CLINIQUE.MEDECINS
SET STATUT = 'ACTIF'
WHERE ID_MEDECINS = 5;

UPDATE CLINIQUE.MEDECINS
SET STATUT = 'INACTIF'
WHERE ID_MEDECINS = 6;

UPDATE CLINIQUE.MEDECINS
SET STATUT = 'ACTIF'
WHERE ID_MEDECINS = 7;

UPDATE CLINIQUE.MEDECINS
SET STATUT = 'EN CONGE'
WHERE ID_MEDECINS = 8;

UPDATE CLINIQUE.MEDECINS
SET STATUT = 'ACTIF'
WHERE ID_MEDECINS = 9;

UPDATE CLINIQUE.MEDECINS
SET STATUT = 'SUSPENDU'
WHERE ID_MEDECINS = 10;



--INSERTION MEDICAMENT

INSERT INTO CLINIQUE.MEDICAMENTS (NOM_MEDICAMENT, DCI, CATEGORIE, PRIX_UNITAIRE, STOCK)
VALUES
('OMEPRAZOLE','OMEPRAZOLE','ANTIACIDES',150.10,50),
('GAVISCON','ALGINATE DE SODIUM','ANTIACIDES',120.07,30),
('CODEINE','CODEINE','ANTITUSSIFS',200.09,40),
('DEXTROMETHORPHANE','DEXTROMETHORPHANE','ANTITUSSIFS',180.00,25),
('COLCHICINE','COLCHICINE','ANTIGOUTTEUX',250.00,20),
('ALLOPURINOL','ALLOPURINOL','ANTIGOUTTEUX',300.70,15),
('AMOXICILLINE','AMOXICILLINE','ANTIBIOTIQUE',100.00,60),
('CIPROFLOXACINE','CIPROFLOXACINE','ANTIBIOTIQUE',220.00,35),
('AZITHROMYCINE','AZITHROMYCINE','ANTIBIOTIQUE',280.00,40),
('CEFTRIAXONE','CEFTRIAXONE','ANTIBIOTIQUE',350.30,25);

-- INSERTION PRESCRIPTIONS
INSERT INTO CLINIQUE.PRESCRIPTION
(POSOLOGIE, DUREE_JOUR, QUANTITE, ID_MEDICAMENTS, ID_CONSULTATIONS)
VALUES
('1 COMPRIME MATIN ET SOIR',7,14,1,13),
('2 COMPRIMES PAR JOUR',5,10,2,16),
('1 COMPRIME PAR JOUR',10,10,3,19),
('1 INJECTION PAR JOUR',3,3,4,21),
('1 COMPRIME MATIN',15,15,5,22),
('1 COMPRIME SOIR',7,7,6,24),
('1 COMPRIME MATIN ET SOIR',10,20,7,25),
('2 COMPRIMES MATIN ET SOIR',5,20,8,30),
('1 COMPRIME PAR JOUR',7,7,9,13),
('1 COMPRIME MATIN ET SOIR',14,28,10,16),
('1 COMPRIME MATIN',10,10,1,19),
('1 COMPRIME SOIR',7,7,2,21),
('1 COMPRIME PAR JOUR',5,5,3,22),
('2 COMPRIMES PAR JOUR',7,14,4,24),
('1 COMPRIME MATIN ET SOIR',10,20,5,25);

--INSERTION FACTURES

INSERT INTO CLINIQUE.FACTURE
(MONTANT_BASE, REMISE, STATUT, DATE_FATURE, ID_CONSULTATIONS)
VALUES
(2500.00, 0, 'EN ATTENT', '2026-01-15', 13),
(1800.00, 5, 'PAYER', '2026-02-10', 16),
(3000.66, 10, 'IMPAYER', '2023-03-05', 19),
(2200.00, 0, 'PAYER', '2025-04-12', 21),
(2100.98, 15, 'EN ATTENT', '2023-05-20', 22),
(1900.00, 0, 'PAYER', '2021-06-18',24),
(2000.00, 5, 'IMPAYER', '2023-07-25', 25),
(2800.45, 0, 'PAYER', '2022-08-30', 30),
(2600.00, 10, 'EN ATTENT', '2023-09-14', 13),
(2400.61, 0, 'PAYER', '2024-10-07', 16),
(3100.00, 20, 'IMPAYER', '2025-11-11', 19),
(2700.30, 0, 'PAYER', '2023-12-22', 21);

--INSERTION AUDIT_CONNEXIONS

INSERT INTO CLINIQUE.AUDIT_CONNEXIONS (UTILISATEUR, TYPE_ACTION, TABLE_CIBLE)
VALUES
('ADMINISTRATEUR','CONECXION','MEDECINS'),
('UTILISATEUR1','DECONNEXION','PATIENTS'),
('UTILISATEUR2','MODIFICATION','CONSULTATIONS'),
('UTILISATEUR3','CONECXION','FACTURE'),
('UTILISATEUR4','MODIFICATION','MEDICAMENTS');



--MIS A JOUR NOTES INTERNES POUR TABLE CONSULTATIONS
UPDATE CLINIQUE.CONSULTATIONS
SET NOTES_INTERNES = 'PATIENT AVEC ANTECEDENTS CARDIAQUES, SUIVI NECESSAIRE'
WHERE ID_CONSULTATIONS = 13;

UPDATE CLINIQUE.CONSULTATIONS
SET NOTES_INTERNES = 'PEDIATRIE : PATIENT EN BONNE EVOLUTION, CONTROLE DANS 1 MOIS'
WHERE ID_CONSULTATIONS = 16;

UPDATE CLINIQUE.CONSULTATIONS
SET NOTES_INTERNES = 'DIAGNOSTIC DE FRACTURE CONFIRME, PRESCRIPTION D�IMMOBILISATION'
WHERE ID_CONSULTATIONS = 19;

UPDATE CLINIQUE.CONSULTATIONS
SET NOTES_INTERNES = 'OPHTALMOLOGIE : PATIENT AVEC CATARACTE, INTERVENTION PROGRAMMEE'
WHERE ID_CONSULTATIONS = 21;

UPDATE CLINIQUE.CONSULTATIONS
SET NOTES_INTERNES = 'GYNECOLOGIE : SUIVI PRENATAL, PATIENTE STABLE'
WHERE ID_CONSULTATIONS = 22;

UPDATE CLINIQUE.CONSULTATIONS
SET NOTES_INTERNES = 'DERMATOLOGIE : ALLERGIE CUTANEE, TRAITEMENT TOPIQUE PRESCRIT'
WHERE ID_CONSULTATIONS = 24;

UPDATE CLINIQUE.CONSULTATIONS
SET NOTES_INTERNES = 'NEUROLOGIE : MIGRAINE RECURRENTE, EXAMENS COMPLEMENTAIRES DEMANDES'
WHERE ID_CONSULTATIONS = 25;

UPDATE CLINIQUE.CONSULTATIONS
SET NOTES_INTERNES = 'CARDIOLOGIE : ANGINE DE POITRINE, PATIENT SOUS SURVEILLANCE'
WHERE ID_CONSULTATIONS = 30;

UPDATE CLINIQUE.CONSULTATIONS
SET NOTES_INTERNES = 'CONSULTATION GENERALE : PATIENT AVEC DIABETE, EDUCATION THERAPEUTIQUE'
WHERE ID_CONSULTATIONS = 20;

UPDATE CLINIQUE.CONSULTATIONS
SET NOTES_INTERNES = 'PEDIATRIE : VARICELLE, PATIENT EN ISOLEMENT DOMICILE'
WHERE ID_CONSULTATIONS = 26;


--MIS A JOUR POUR LA COLONE SPECIALIATIONS_COMPLEMENTAIRE
UPDATE CLINIQUE.MEDECINS
SET SPECIALISATIONS_COMPLEMENTAIRE = 'ENDOCRINOLOGIE'
WHERE ID_MEDECINS = 1;

UPDATE CLINIQUE.MEDECINS
SET SPECIALISATIONS_COMPLEMENTAIRE = 'NEONATOLOGIE'
WHERE ID_MEDECINS = 3;

UPDATE CLINIQUE.MEDECINS
SET SPECIALISATIONS_COMPLEMENTAIRE = 'DERMATOLOGIE'
WHERE ID_MEDECINS = 5;

UPDATE CLINIQUE.MEDECINS
SET SPECIALISATIONS_COMPLEMENTAIRE = 'NEUROCHIRURGIE'
WHERE ID_MEDECINS = 6;

UPDATE CLINIQUE.MEDECINS
SET SPECIALISATIONS_COMPLEMENTAIRE = 'ONCOLOGIE'
WHERE ID_MEDECINS = 8;

-- REQUETE
--4.1 
SELECT M.MATRICULE,(M.NOM+'  '+PRENOM) AS NOM_COMPLET,
M.EMAIL,S.NOM_SPECIALITE AS SPECIALITE FROM 
CLINIQUE.MEDECINS AS M INNER JOIN CLINIQUE.SPECIALITE AS S ON M.ID_SPECIALITE= S.ID_SPECIALITE
ORDER BY S.NOM_SPECIALITE,M.NOM;


--4.2

SELECT P.NUMERO_PATIENT,(P.NOM+'  '+P.PRENOM) AS NOM_COMPLET,
P.DATE_NAISSANCE,DATEDIFF(YEAR,P.DATE_NAISSANCE,GETDATE()) AS AGE FROM CLINIQUE.PATIENTS AS P 
WHERE P.DATE_NAISSANCE >'1990-01-01' ORDER BY P.DATE_INSCRIPTIONS DESC;


--4.3
SELECT C.ID_CONSULTATIONS,C.MOTIF,C.STATUT,FORMAT(C.DATE_CONSULTATIONS,'dd/MM/yyy') AS DATE_CONSULTATIONS
FROM CLINIQUE.CONSULTATIONS AS C WHERE C.STATUT ='TERMINER' AND YEAR (C.DATE_CONSULTATIONS)=2024
ORDER BY C.DATE_CONSULTATIONS DESC ;

--4.4
SELECT TOP 5 WITH TIES M.DCI AS NOM_COMMERCIAL ,M.CATEGORIE,M.PRIX_UNITAIRE 
FROM CLINIQUE.MEDICAMENTS AS M ORDER BY M.PRIX_UNITAIRE DESC;


--4.2  AGREGATION ET GROUP BY
--4.5

SELECT (M.NOM +'  '+ M.PRENOM) AS NOM_COMPLET , S.NOM_SPECIALITE AS SPECIALITE ,
COUNT (C.ID_CONSULTATIONS) AS TOTAL_CONSULTATIONS,
COUNT (CASE WHEN C.STATUT ='TERMINER' THEN 1 END ) AS CONSULTATIONS_TERMINER
FROM CLINIQUE.MEDECINS AS M INNER JOIN CLINIQUE.SPECIALITE AS S ON M.ID_SPECIALITE = S.ID_SPECIALITE
LEFT JOIN CLINIQUE.CONSULTATIONS AS C ON M.ID_MEDECINS = C.ID_MEDECINS
GROUP BY M.NOM,M.PRENOM,S.NOM_SPECIALITE
ORDER BY TOTAL_CONSULTATIONS DESC;


--4.6
SELECT 
    S.NOM_SPECIALITE AS SPECIALITE,
    COUNT(F.ID_FACTURES) AS NOMBRE_FACTURES_PAYEES,
    ROUND(SUM(F.MONTANT_NET), 2) AS CHIFFRE_AFFAIRES
FROM CLINIQUE.FACTURE AS F INNER JOIN CLINIQUE.CONSULTATIONS AS C
    ON F.ID_CONSULTATIONS = C.ID_CONSULTATIONS INNER JOIN CLINIQUE.MEDECINS AS M
    ON C.ID_MEDECINS = M.ID_MEDECINS
INNER JOIN CLINIQUE.SPECIALITE AS S
    ON M.ID_SPECIALITE = S.ID_SPECIALITE
WHERE F.STATUT = 'PAYER'
GROUP BY S.NOM_SPECIALITE
HAVING SUM(F.MONTANT_NET) > 2000
ORDER BY CHIFFRE_AFFAIRES  DESC;


--4.7
SELECT  P.SEXE ,COUNT(P.ID_PATIENTS) AS NOMBRE_PATIENTS,
ROUND (AVG(DATEDIFF(YEAR,P.DATE_NAISSANCE,GETDATE())),1)  AS  MOYENNE_AGE ,
 MIN(P.DATE_NAISSANCE)  AS PLUS_AGE,
 MAX(P.DATE_NAISSANCE) AS PLUS_JEUNE
 FROM CLINIQUE.PATIENTS AS P GROUP BY P.SEXE;


--4.8 
SELECT M.NOM_MEDICAMENT ,
M.CATEGORIE,
COALESCE(M.STOCK,0) AS STOCK ,
CASE WHEN COALESCE (M.STOCK,0 ) <20 THEN 'CRITIQUE' ELSE 'FAIBLE'
END AS NIVEAU_ALERTE FROM CLINIQUE.MEDICAMENTS AS M 
WHERE COALESCE (M.STOCK,0) <=50;

--4.9
SELECT FORMAT(C.DATE_CONSULTATIONS, 'yyyy-MM') AS Mois,
    COUNT(C.ID_CONSULTATIONS) AS TotalConsultations,
    COUNT(CASE WHEN C.STATUT = 'TERMINER' THEN 1 END) AS ConsultationsTerminees,
    ROUND(
        CAST(COUNT(CASE WHEN C.STATUT = 'TERMINER' THEN 1 END) AS FLOAT) 
        / NULLIF(COUNT(C.ID_CONSULTATIONS), 0) * 100, 
        1
    ) AS TauxRealisation
FROM CLINIQUE.CONSULTATIONS AS C
WHERE YEAR(C.DATE_CONSULTATIONS) = 2024
GROUP BY FORMAT(C.DATE_CONSULTATIONS, 'yyyy-MM')
ORDER BY Mois;

--5 DML JOINTURES 
--5.1 INNER JOIN

SELECT C.DATE_CONSULTATIONS,
P.NOM + ' ' + P.PRENOM AS NOM_CONPLET_PATIENT,
M.NOM + ' ' + M.PRENOM  AS NOM_COMPLET_MEDECINS,
MD.DCI AS NOM_COMMERTIAL,
PC.POSOLOGIE,
PC.DUREE_JOUR,
PC.QUANTITE AS QUANTITE_PRESCRIPTIONS
FROM CLINIQUE.PRESCRIPTION AS PC 
INNER JOIN CLINIQUE.CONSULTATIONS AS C ON PC.ID_CONSULTATIONS  = C.ID_CONSULTATIONS
INNER JOIN CLINIQUE.MEDICAMENTS AS MD ON MD.ID_MEDICAMENTS=PC.ID_MEDICAMENTS
INNER JOIN CLINIQUE.MEDECINS AS M ON M.ID_MEDECINS =C.ID_MEDECINS
INNER JOIN CLINIQUE.PATIENTS AS P ON P.ID_PATIENTS=C.ID_PATIENTS
ORDER BY
C.DATE_CONSULTATIONS DESC;


--5.2 FACTURES PAYEE AVEC DETAILLE

SELECT F.ID_FACTURES AS NUMERO_FACTURE,
F.DATE_FACTURE AS DATE_FACTURATION,
P.NOM,M.NOM,F.MONTANT_BASE,F.REMISE,F.MONTANT_NET
FROM CLINIQUE.FACTURE AS F 
INNER JOIN CLINIQUE.CONSULTATIONS AS C ON C.ID_CONSULTATIONS = F.ID_CONSULTATIONS
INNER JOIN CLINIQUE.PATIENTS AS P ON P.ID_PATIENTS =C.ID_PATIENTS
INNER JOIN CLINIQUE.MEDECINS AS M ON M.ID_MEDECINS = C.ID_MEDECINS
WHERE F.STATUT='PAYER';


--5.3 PATIENTS SAN AUCUNE CONSULTATIONS
SELECT P.NUMERO_PATIENT AS NUMERO_DOSSIER,
P.NOM + ' ' +P.PRENOM AS NOM_COMPLET,
P.DATE_INSCRIPTIONS FROM CLINIQUE.PATIENTS AS P 
LEFT JOIN CLINIQUE.CONSULTATIONS AS C ON P.ID_PATIENTS= C.ID_PATIENTS
WHERE C.ID_CONSULTATIONS IS NULL;

--5.4  REVENUE PAR MEDECINS

SELECT M.NOM ,
S.NOM_SPECIALITE AS SPECIALITE , COALESCE(SUM(F.MONTANT_NET),0) AS TOTAL_FACTURE_PAYEE
FROM CLINIQUE.MEDECINS AS M LEFT JOIN CLINIQUE.CONSULTATIONS AS C ON M.ID_MEDECINS =C.ID_MEDECINS
LEFT JOIN CLINIQUE.FACTURE AS F ON C.ID_CONSULTATIONS = F.ID_CONSULTATIONS
LEFT JOIN CLINIQUE.SPECIALITE AS S ON M.ID_SPECIALITE= S.ID_SPECIALITE
AND  F.STATUT='PAYER'
GROUP BY M.NOM,S.NOM_SPECIALITE 
ORDER BY TOTAL_FACTURE_PAYEE DESC;

--5.4 FULL OUTER JOIN
--5.5 INVENTAIRE SPECIALITES E MEDECINS

SELECT COALESCE(S.NOM_SPECIALITE,'PAS DE SPECIALITE') AS SPECILAITE,
COALESCE(M.NOM + ' ' + M.PRENOM,'PAS DE MEDECINS') AS NOM_MEDECINS 
FROM CLINIQUE.SPECIALITE AS S
FULL OUTER JOIN CLINIQUE.MEDECINS AS M
ON S.ID_SPECIALITE = M.ID_SPECIALITE ;

--5.4 AUTO-JOINT
--5.6 PATIENS AYANNT PLUSIEUR MEDECINS #TS

SELECT P.NOM + ' ' + P.PRENOM AS NOM_PATIENTS ,
COUNT (DISTINCT C.ID_MEDECINS) AS NOMBRE_DE_MEDECINS_#
FROM CLINIQUE.PATIENTS AS P 
INNER JOIN CLINIQUE.CONSULTATIONS AS C ON P.ID_PATIENTS = C.ID_PATIENTS
GROUP BY P.NOM, PRENOM HAVING COUNT( DISTINCT C.ID_MEDECINS) >=2;

--5.5 OUTER APPLY
--5.7 DERNIERE CONSULTATIONS PARPATIENT

SELECT P.NOM + ' ' + P.PRENOM AS NOM_PATIENT,
DC.DATE_CONSULTATIONS,
DC.MOTIF,
DC.NOM_MEDECINS FROM CLINIQUE.PATIENTS AS P OUTER APPLY ( SELECT TOP 1
 C.DATE_CONSULTATIONS AS DATE_CONSULTATIONS , C.MOTIF AS MOTIF,
 M.NOM + ' ' + M.PRENOM AS NOM_MEDECINS FROM CLINIQUE.CONSULTATIONS AS C 
 INNER JOIN CLINIQUE.MEDECINS AS M ON C.ID_MEDECINS = M.ID_MEDECINS 
 WHERE C.ID_PATIENTS = P.ID_PATIENTS ORDER BY C.DATE_CONSULTATIONS DESC)
 AS DC;


 --5.8  CONSULTATIONS AVEC LEUR PRESCRIPTIONS 

SELECT 
    C.DATE_CONSULTATIONS,
    P.NOM + ' ' + P.PRENOM AS NOM_PATIENT,
    PR.MEDICAMENT
FROM CLINIQUE.CONSULTATIONS AS C
INNER JOIN CLINIQUE.PATIENTS AS P 
    ON C.ID_PATIENTS = P.ID_PATIENTS
CROSS APPLY (
    SELECT M.NOM_MEDICAMENT AS MEDICAMENT
    FROM CLINIQUE.PRESCRIPTION AS PR
    INNER JOIN CLINIQUE.MEDICAMENTS AS M 
        ON PR.ID_MEDICAMENTS = M.ID_MEDICAMENTS
    WHERE PR.ID_CONSULTATIONS = C.ID_CONSULTATIONS
) AS PR
WHERE C.STATUT = 'TERMINER'
ORDER BY C.DATE_CONSULTATIONS, NOM_PATIENT;

